### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by kk-mofux** [G-dH/gnome-shell-extension-overview-keyboard-navigation#1]
Thanks for this extension, very usefull. Do you have plans to upstream these changes?

**Comment by G-dH** [comment]
This issue is fixed for GS 42, it's known bug. My extension is kind of workaround and I'm not exactly sure why the keyboard events don't get to the code they should...

**Comment by kk-mofux** [comment]
Great and thanks for clearing this up!
